### ISSUE TITLE
Could not find `init` in the `_sqh` upon library loading

### ISSUE THREAD

**Issue by asteinlein** [segment-integrations/analytics.js-integration-saasquatch#3]
Having configured and enabled the integration, I get `Could not find "init" in the _sqh queue when squatch.js was loaded.` in the console. Seems like their snippet expects init to be queued before the script itself is loaded?

**Comment by hankim813** [comment]
@asteinlein it looks like we're pushing the `init` object only inside the `.identify()` and `.group()` calls rather than initialization of the library:

https://github.com/segment-integrations/analytics.js-integration-saasquatch/blob/master/lib/index.js#L78
https://github.com/segment-integrations/analytics.js-integration-saasquatch/blob/master/lib/index.js#L107

Definitely going to check this out and modify the `.initialize()` block to push the `init` object if the library is looking for it!
